SELECT APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT P
         JOIN APPOINTMENT A
         JOIN DOCTOR D
              ON P.PT_NO = A.PT_NO AND A.MDDR_ID = D.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y%m%d') = '20220413'
  AND D.MCDP_CD = 'CS'
  AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC;