SELECT YEAR (SALES_DATE) AS 'YEAR', MONTH (SALES_DATE) AS 'MONTH', GENDER AS 'GENDER', COUNT (DISTINCT UI.USER_ID) AS 'USERS'
FROM USER_INFO UI JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;