SELECT SUM(SCORE) AS 'SCORE', HE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HE
         JOIN HR_GRADE HG
              ON HE.EMP_NO = HG.EMP_NO
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC LIMIT 1;