SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS 'TOTAL_SALES'
FROM BOOK B
         JOIN AUTHOR A
         JOIN BOOK_SALES BS
              ON B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;