SELECT YEAR (DIFFERENTIATION_DATE) AS 'YEAR', MAX_SIZE - SIZE_OF_COLONY AS 'YEAR_DEV', A.ID
FROM ECOLI_DATA A JOIN (
    SELECT YEAR (DIFFERENTIATION_DATE) AS 'YEAR', MAX (SIZE_OF_COLONY) AS 'MAX_SIZE'
    FROM ECOLI_DATA B
    GROUP BY YEAR
    ) B
ON YEAR (A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR (DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC;
