SELECT FP.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) AS 'TOTAL_SALES'
FROM FOOD_PRODUCT FP
         JOIN FOOD_ORDER FO
              ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE YEAR (PRODUCE_DATE) = 2022 AND MONTH (PRODUCE_DATE) = 5
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC;
